; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\maksi\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
